name: InstallPrometheusPushGateway
description: 'Installs prometheus pushgateway'
inputs:
  cluster_name:
    description: 'Name of the cluster to be launched by eksctl'
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out. Requires a corresponding Karpenter snapshot release"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.git_ref }}
    - uses: ./.github/actions/e2e/install-helm
    - name: add prometheus repo
      shell: bash
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - name: create prometheus namespace
      shell: bash
      run: |
        kubectl create ns prometheus || true
        kubectl label ns prometheus scrape=enabled --overwrite=true
    - name: install prometheus
      shell: bash
      run: |
        helm upgrade --install prometheus-pushgateway prometheus-community/prometheus-pushgateway \
          -n prometheus \
          -f ./.github/actions/e2e/install-prometheus-pushgateway/values.yaml \
          --set serviceMonitor.relabelings[0].targetLabel=clusterName \
          --set serviceMonitor.relabelings[0].replacement=${{ inputs.cluster_name }} \
          --set serviceMonitor.relabelings[1].targetLabel=gitRef \
          --set serviceMonitor.relabelings[1].replacement=$(git rev-parse HEAD) \
          --set serviceMonitor.relabelings[2].targetLabel=mostRecentTag \
          --set serviceMonitor.relabelings[2].replacement=$(git describe --abbrev=0 --tags) \
          --set serviceMonitor.relabelings[3].targetLabel=commitsAfterTag \
          --set serviceMonitor.relabelings[3].replacement=$(git describe --tags | cut -d '-' -f 2)