name: MaintainerCheck
description: 'Checks if a given username belongs is part of a maintainers list and fails when it is not'
inputs:
  username:
    description: 'Username to be checked'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      with:
        script: |
          const result = await github.rest.teams.getMembershipForUserInOrg({
            org: context.repo.owner,
            team_slug: 'karpenter',
            username: ${{ inputs.username }}
          })
          console.log(creator, result)
