name: E2ETestMatrix
on:
  schedule:
    - cron: '7 */6 * * *'
  push:
    branches: [main]
  workflow_run:
    workflows: [ApprovalComment]
    types: [completed]
  workflow_dispatch:
  pull_request:
jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        suite: [Integration, Machine, Consolidation, Utilization, Interruption, Drift, Chaos, IPv6]
    uses: ./.github/workflows/e2e.yaml
    with:
      suite: ${{ matrix.suite }}
      git_repo: jonathan-innis/karpenter
  e2e-upgrade:
    uses: ./.github/workflows/e2e-upgrade.yaml
    with:
      git_repo: jonathan-innis/karpenter
      from_git_ref: v0.26.1